/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "simple_switch_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace sswitch_runtime {

int _kMirroringOperationErrorCodeValues[] = {
  MirroringOperationErrorCode::SESSION_NOT_FOUND
};
const char* _kMirroringOperationErrorCodeNames[] = {
  "SESSION_NOT_FOUND"
};
const std::map<int, const char*> _MirroringOperationErrorCode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(1, _kMirroringOperationErrorCodeValues, _kMirroringOperationErrorCodeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


MirroringSessionConfig::~MirroringSessionConfig() throw() {
}


void MirroringSessionConfig::__set_port(const int32_t val) {
  this->port = val;
__isset.port = true;
}

void MirroringSessionConfig::__set_mgid(const int32_t val) {
  this->mgid = val;
__isset.mgid = true;
}

const char* MirroringSessionConfig::ascii_fingerprint = "C1241AF5AA92C586B664FD41DC97C576";
const uint8_t MirroringSessionConfig::binary_fingerprint[16] = {0xC1,0x24,0x1A,0xF5,0xAA,0x92,0xC5,0x86,0xB6,0x64,0xFD,0x41,0xDC,0x97,0xC5,0x76};

uint32_t MirroringSessionConfig::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->port);
          this->__isset.port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->mgid);
          this->__isset.mgid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t MirroringSessionConfig::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("MirroringSessionConfig");

  if (this->__isset.port) {
    xfer += oprot->writeFieldBegin("port", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32(this->port);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.mgid) {
    xfer += oprot->writeFieldBegin("mgid", ::apache::thrift::protocol::T_I32, 2);
    xfer += oprot->writeI32(this->mgid);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(MirroringSessionConfig &a, MirroringSessionConfig &b) {
  using ::std::swap;
  swap(a.port, b.port);
  swap(a.mgid, b.mgid);
  swap(a.__isset, b.__isset);
}

MirroringSessionConfig::MirroringSessionConfig(const MirroringSessionConfig& other0) {
  port = other0.port;
  mgid = other0.mgid;
  __isset = other0.__isset;
}
MirroringSessionConfig& MirroringSessionConfig::operator=(const MirroringSessionConfig& other1) {
  port = other1.port;
  mgid = other1.mgid;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const MirroringSessionConfig& obj) {
  using apache::thrift::to_string;
  out << "MirroringSessionConfig(";
  out << "port="; (obj.__isset.port ? (out << to_string(obj.port)) : (out << "<null>"));
  out << ", " << "mgid="; (obj.__isset.mgid ? (out << to_string(obj.mgid)) : (out << "<null>"));
  out << ")";
  return out;
}


InvalidMirroringOperation::~InvalidMirroringOperation() throw() {
}


void InvalidMirroringOperation::__set_code(const MirroringOperationErrorCode::type val) {
  this->code = val;
}

const char* InvalidMirroringOperation::ascii_fingerprint = "8BBB3D0C3B370CB38F2D1340BB79F0AA";
const uint8_t InvalidMirroringOperation::binary_fingerprint[16] = {0x8B,0xBB,0x3D,0x0C,0x3B,0x37,0x0C,0xB3,0x8F,0x2D,0x13,0x40,0xBB,0x79,0xF0,0xAA};

uint32_t InvalidMirroringOperation::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->code = (MirroringOperationErrorCode::type)ecast2;
          this->__isset.code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t InvalidMirroringOperation::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("InvalidMirroringOperation");

  xfer += oprot->writeFieldBegin("code", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(InvalidMirroringOperation &a, InvalidMirroringOperation &b) {
  using ::std::swap;
  swap(a.code, b.code);
  swap(a.__isset, b.__isset);
}

InvalidMirroringOperation::InvalidMirroringOperation(const InvalidMirroringOperation& other3) : TException() {
  code = other3.code;
  __isset = other3.__isset;
}
InvalidMirroringOperation& InvalidMirroringOperation::operator=(const InvalidMirroringOperation& other4) {
  code = other4.code;
  __isset = other4.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const InvalidMirroringOperation& obj) {
  using apache::thrift::to_string;
  out << "InvalidMirroringOperation(";
  out << "code=" << to_string(obj.code);
  out << ")";
  return out;
}

} // namespace
