/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "simple_switch_constants.h"

namespace sswitch_runtime {

const simple_switchConstants g_simple_switch_constants;

simple_switchConstants::simple_switchConstants() {
}

} // namespace

